---
title: "Hell World"
date: 2021-05-12
---

title: Hell World
author: youngyeong
email: tlsznl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  안녕하세요 코딩 처음 시작하는 코린이입니다. 아직 연습 중이니 이상한게 있어도
  걱정하지 말아주세요 처음이니 봐주세요

# social links
twitter_username: No twitter # DO NOT include the @ character, or else the build will fail!
github_username:  youngyeong # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
